FROM node:10 as builder
RUN mkdir /usr/local/app
ADD . /usr/local/app
WORKDIR /usr/local/app/client
RUN npm install -g @angular/cli && npm install --force
RUN npm rebuild node-sass
RUN ng build --prod="true"

FROM linuxserver/letsencrypt
COPY --from=builder /usr/local/app/dist/* /config/www
COPY api.subfolder.conf /config/nginx/proxy-confs/api.subfolder.conf
EXPOSE 80 433