version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: false

      - run: |
          docker build -t rsenuatnu.azurecr.io/hands-on-app:latest -t rsenuatnu.azurecr.io/hands-on-app:$CIRCLE_SHA1 .
          docker login -u $DOCKER_USER -p $DOCKER_PASS rsenuatnu.azurecr.io
          docker push rsenuatnu.azurecr.io/hands-on-app:latest
          docker push rsenuatnu.azurecr.io/hands-on-app:$CIRCLE_SHA1


workflows:
  version: 2
  build:
    jobs:
      - build:
          context: atnu-context
